language: cpp

compiler:
  - gcc
  - clang
  
env:
  - GAZEBO_YARP_PLUGINS_BUILD_TYPE=Debug
  - GAZEBO_YARP_PLUGINS_BUILD_TYPE=Release


before_script:
  - sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu precise main" > /etc/apt/sources.list.d/gazebo-latest.list'
  - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get --force-yes install libtinyxml-dev gazebo libboost-system-dev libace-dev
  - git clone https://github.com/robotology/yarp
  - cd yarp
  - mkdir build
  - cd build
  - cmake -DCREATE_SHARED_LIBRARY:BOOL=ON -DCMAKE_BUILD_TYPE=${GAZEBO_YARP_PLUGINS_BUILD_TYPE} ..
  - make
  - sudo make install
  - cd ../..
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${GAZEBO_YARP_PLUGINS_BUILD_TYPE} ./..


script: make 

notifications:
  email:
    - pegua1@gmail.com
