language: cpp

compiler:
  - gcc
  - clang
  
env:
  - GAZEBO_YARP_PLUGINS_BUILD_TYPE=Debug
  - GAZEBO_YARP_PLUGINS_BUILD_TYPE=Release

before_script:
  - git clone https://github.com/robotology/yarp
  - cd yarp
  - mkdir build
  - cd build
  - cmake -DCREATE_SHARED_LIBRARY:BOOL=ON -DCMAKE_INSTALL_PREFIX="./local_install" -DCMAKE_BUILD_TYPE=${CODYCO_TRAVIS_BUILD_TYPE} ..
  - make 
  - make install
  - cd ../..
  - sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu precise main" > /etc/apt/sources.list.d/gazebo-latest.list'
  - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
  - sudo apt-get update 
  - sudo apt-get --force-yes install icub libtinyxml-dev gazebo libboost-system-dev
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${GAZEBO_YARP_PLUGINS_BUILD_TYPE} ./..

script: make 

notifications:
  email:
    - pegua1@gmail.com
